modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://example.invalid/zonacraft"

[[mods]]
modId = "stalker"
version = "${file.jarVersion}"
displayName = "ZONACRAFT Port"
authors = "ZONACRAFT Team"
description = '''
Incremental Forge 1.20.1 port of legacy ZONACRAFT content.
'''

[[dependencies.stalker]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stalker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
