package ru.zonecraft.armorbootfix;

import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Map;

final class SuitDetector {
    private static final String SUIT_CLASS =
            "ru.stalcraft.glbarmor.item.ItemStalcraftSuit";

    private SuitDetector() {
    }

    static boolean wearsGlbSuit(Object living) {
        if (living == null) {
            return false;
        }

        int slot;
        for (slot = 1; slot <= 4; slot++) {
            Object stack = invoke(living,
                    new String[] {"getCurrentItemOrArmor", "func_71124_b", "func_130225_q"},
                    new Class[] {Integer.TYPE},
                    new Object[] {Integer.valueOf(slot)});
            if (isSuitStack(stack)) {
                return true;
            }
        }

        Object inventory = field(living,
                new String[] {"inventory", "field_71071_by"});
        if (inventory == null) {
            return false;
        }

        for (slot = 0; slot < 4; slot++) {
            Object stack = invoke(inventory,
                    new String[] {"armorItemInSlot"},
                    new Class[] {Integer.TYPE},
                    new Object[] {Integer.valueOf(slot)});
            if (isSuitStack(stack)) {
                return true;
            }
        }

        Object armor = field(inventory,
                new String[] {"armor", "armorInventory", "field_70460_b"});
        if (armor instanceof Map) {
            @SuppressWarnings("rawtypes")
            Map map = (Map) armor;
            for (slot = 0; slot < 4; slot++) {
                if (isSuitStack(map.get(Integer.valueOf(slot)))) {
                    return true;
                }
            }
        } else if (armor != null && armor.getClass().isArray()) {
            int length = Array.getLength(armor);
            for (slot = 0; slot < length; slot++) {
                if (isSuitStack(Array.get(armor, slot))) {
                    return true;
                }
            }
        }
        return false;
    }

    static boolean isSneaking(Object living) {
        Object value = invoke(living,
                new String[] {"isSneaking", "func_70093_af"},
                new Class[0], new Object[0]);
        return value instanceof Boolean && ((Boolean) value).booleanValue();
    }

    static boolean isOnGround(Object living) {
        Object value = field(living,
                new String[] {"onGround", "field_70122_E"});
        return !(value instanceof Boolean) || ((Boolean) value).booleanValue();
    }

    private static boolean isSuitStack(Object stack) {
        Object item = invoke(stack,
                new String[] {"getItem", "func_77973_b"},
                new Class[0], new Object[0]);
        if (item == null) {
            item = field(stack, new String[] {"item", "field_151002_e"});
        }
        if (item == null) {
            return false;
        }

        Class<?> type = item.getClass();
        while (type != null && type != Object.class) {
            String name = type.getName();
            if (SUIT_CLASS.equals(name)) {
                return true;
            }
            // Keeps the patch compatible with renamed subclasses generated by
            // later armor versions while avoiding ordinary vanilla armor.
            if (name.startsWith("ru.stalcraft.glbarmor.")
                    && name.toLowerCase().indexOf("suit") >= 0) {
                return true;
            }
            type = type.getSuperclass();
        }
        return false;
    }

    private static Object field(Object target, String[] names) {
        if (target == null) {
            return null;
        }
        Class<?> type = target.getClass();
        while (type != null && type != Object.class) {
            int index;
            for (index = 0; index < names.length; index++) {
                try {
                    Field field = type.getDeclaredField(names[index]);
                    field.setAccessible(true);
                    return field.get(target);
                } catch (Throwable ignored) {
                }
            }
            type = type.getSuperclass();
        }
        return null;
    }

    private static Object invoke(Object target, String[] names,
                                 Class[] parameters, Object[] arguments) {
        if (target == null) {
            return null;
        }
        Class<?> type = target.getClass();
        while (type != null && type != Object.class) {
            int index;
            for (index = 0; index < names.length; index++) {
                try {
                    Method method = type.getDeclaredMethod(names[index], parameters);
                    method.setAccessible(true);
                    return method.invoke(target, arguments);
                } catch (Throwable ignored) {
                }
            }
            type = type.getSuperclass();
        }
        return null;
    }
}
